name: Download Godot source code
description: Download and extract the Godot source code for use in compiling
inputs:
  version:
    description: Version of Godot source code to download
    default: "3.5-stable"
runs:
  using: "composite"
  steps:
    - name: Download and extract Godot
      shell: bash
      run: |
        ls
        mkdir PID
        mv ./* ./PID
        ls
        curl -fLO https://github.com/godotengine/godot/archive/${{ inputs.version }}.tar.gz
        tar -xvzf ${{ inputs.version }}.tar.gz --strip-components 1 --exclude=".github"

    # Custom steps to download and moving sg-physics to the modules folder. 
    - name: Download PID-Module
      shell: bash
      run: |
        git clone https://github.com/${{ github.repository }}

