name: Download Godot source code
description: Download and extract the Godot source code for use in compiling
inputs:
  version:
    description: Version of Godot source code to download
    default: "3.5-stable"
runs:
  using: "composite"
  steps:
    - name: Download and extract Godot
      shell: bash
      run: |
        rm -R ./"PID Controller Godot Module"
        ls >> output.txt
        mkdir pid
        cat output.txt | awk '{system("mv " $0 " ./pid")}'
        curl -fLO https://github.com/godotengine/godot/archive/${{ inputs.version }}.tar.gz
        tar -xvzf ${{ inputs.version }}.tar.gz --strip-components 1 --exclude=".github"
        mv pid ./modules/pid


    # Custom steps to download and moving sg-physics to the modules folder. 
    #- name: Download PID-Module
    #  shell: bash
    #  run: |
    #    git clone https://github.com/${{ github.repository }}
    #    tree -L 2
    #    mv ./PID ./modules

